### ISSUE TITLE
Gauge Needles

### ISSUE THREAD

**Issue by Braehead** [HASwitchPlate/openHASP-docs#16]
The documentation shows a gauge with multiple needles.  How do you access and display additional needles?

Is this a misleading image in the documentation?  Or is it waiting for a future upgrade, as yet to be released?

Many thanks for a great project, keep up the good work.

Adam.

**Comment by fvanroie** [comment]
Multiple needles are not implemented in openHASP (yet)...
LVGL has many, many APIs to manipulate the objects and in openHASP there is a subset available for use.

The image is taken from the [LVGL widgets documentation](https://docs.lvgl.io/7.11/widgets/gauge.html#simple-gauge) to visualize what the objects look like.
However in case of the gauge, the APIs to address multiple needles is not yet exposed in jsonl.
That image is indeed poorly choosen, since it shows what can be done in LVGL but not yet in openHASP...

**Comment by Braehead** [comment]
Shame, but thank you for the explanation, makes sense.  Could you add this function to the feature requests please?  And you can progress when you are next upgrading that area of the code.  In the meantime, I'll fiddle around with stacking gauges and transparency, or a different display methodology.  But a gauge with 3 or 4 needles would have been ideal.
